// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/trainshard.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TrainshardStatus int32

const (
	TrainshardStatus_TRAINSHARD_STATUS_UNSPECIFIED TrainshardStatus = 0
	TrainshardStatus_TRAINSHARD_STATUS_ACTIVE      TrainshardStatus = 1
	TrainshardStatus_TRAINSHARD_STATUS_SETTLED     TrainshardStatus = 2
	TrainshardStatus_TRAINSHARD_STATUS_EXPIRED     TrainshardStatus = 3
)

var TrainshardStatus_name = map[int32]string{
	0: "TRAINSHARD_STATUS_UNSPECIFIED",
	1: "TRAINSHARD_STATUS_ACTIVE",
	2: "TRAINSHARD_STATUS_SETTLED",
	3: "TRAINSHARD_STATUS_EXPIRED",
}

var TrainshardStatus_value = map[string]int32{
	"TRAINSHARD_STATUS_UNSPECIFIED": 0,
	"TRAINSHARD_STATUS_ACTIVE":      1,
	"TRAINSHARD_STATUS_SETTLED":     2,
	"TRAINSHARD_STATUS_EXPIRED":     3,
}

func (x TrainshardStatus) String() string {
	return proto.EnumName(TrainshardStatus_name, int32(x))
}

func (TrainshardStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4796ed29b8b523a8, []int{0}
}

type TrainshardProposalStatus int32

const (
	TrainshardProposalStatus_TRAINSHARD_PROPOSAL_STATUS_UNSPECIFIED TrainshardProposalStatus = 0
	TrainshardProposalStatus_TRAINSHARD_PROPOSAL_STATUS_OPEN        TrainshardProposalStatus = 1
	TrainshardProposalStatus_TRAINSHARD_PROPOSAL_STATUS_CONSUMED    TrainshardProposalStatus = 2
)

var TrainshardProposalStatus_name = map[int32]string{
	0: "TRAINSHARD_PROPOSAL_STATUS_UNSPECIFIED",
	1: "TRAINSHARD_PROPOSAL_STATUS_OPEN",
	2: "TRAINSHARD_PROPOSAL_STATUS_CONSUMED",
}

var TrainshardProposalStatus_value = map[string]int32{
	"TRAINSHARD_PROPOSAL_STATUS_UNSPECIFIED": 0,
	"TRAINSHARD_PROPOSAL_STATUS_OPEN":        1,
	"TRAINSHARD_PROPOSAL_STATUS_CONSUMED":    2,
}

func (x TrainshardProposalStatus) String() string {
	return proto.EnumName(TrainshardProposalStatus_name, int32(x))
}

func (TrainshardProposalStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4796ed29b8b523a8, []int{1}
}

type TrainshardCloseReason int32

const (
	TrainshardCloseReason_TRAINSHARD_CLOSE_REASON_UNSPECIFIED     TrainshardCloseReason = 0
	TrainshardCloseReason_TRAINSHARD_CLOSE_REASON_SETTLED         TrainshardCloseReason = 1
	TrainshardCloseReason_TRAINSHARD_CLOSE_REASON_TIMEOUT         TrainshardCloseReason = 2
	TrainshardCloseReason_TRAINSHARD_CLOSE_REASON_NO_ACTIVE_NODES TrainshardCloseReason = 3
)

var TrainshardCloseReason_name = map[int32]string{
	0: "TRAINSHARD_CLOSE_REASON_UNSPECIFIED",
	1: "TRAINSHARD_CLOSE_REASON_SETTLED",
	2: "TRAINSHARD_CLOSE_REASON_TIMEOUT",
	3: "TRAINSHARD_CLOSE_REASON_NO_ACTIVE_NODES",
}

var TrainshardCloseReason_value = map[string]int32{
	"TRAINSHARD_CLOSE_REASON_UNSPECIFIED":     0,
	"TRAINSHARD_CLOSE_REASON_SETTLED":         1,
	"TRAINSHARD_CLOSE_REASON_TIMEOUT":         2,
	"TRAINSHARD_CLOSE_REASON_NO_ACTIVE_NODES": 3,
}

func (x TrainshardCloseReason) String() string {
	return proto.EnumName(TrainshardCloseReason_name, int32(x))
}

func (TrainshardCloseReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4796ed29b8b523a8, []int{2}
}

type TrainshardNodeStatus int32

const (
	TrainshardNodeStatus_TRAINSHARD_NODE_STATUS_UNSPECIFIED       TrainshardNodeStatus = 0
	TrainshardNodeStatus_TRAINSHARD_NODE_STATUS_ACTIVE            TrainshardNodeStatus = 1
	TrainshardNodeStatus_TRAINSHARD_NODE_STATUS_AUTOKICKED        TrainshardNodeStatus = 2
	TrainshardNodeStatus_TRAINSHARD_NODE_STATUS_RELEASED_ON_CLOSE TrainshardNodeStatus = 3
)

var TrainshardNodeStatus_name = map[int32]string{
	0: "TRAINSHARD_NODE_STATUS_UNSPECIFIED",
	1: "TRAINSHARD_NODE_STATUS_ACTIVE",
	2: "TRAINSHARD_NODE_STATUS_AUTOKICKED",
	3: "TRAINSHARD_NODE_STATUS_RELEASED_ON_CLOSE",
}

var TrainshardNodeStatus_value = map[string]int32{
	"TRAINSHARD_NODE_STATUS_UNSPECIFIED":       0,
	"TRAINSHARD_NODE_STATUS_ACTIVE":            1,
	"TRAINSHARD_NODE_STATUS_AUTOKICKED":        2,
	"TRAINSHARD_NODE_STATUS_RELEASED_ON_CLOSE": 3,
}

func (x TrainshardNodeStatus) String() string {
	return proto.EnumName(TrainshardNodeStatus_name, int32(x))
}

func (TrainshardNodeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4796ed29b8b523a8, []int{3}
}

type TrainshardReservedNode struct {
	Participant      string               `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	NodeId           string               `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ModelId          string               `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	PocWeight        int64                `protobuf:"varint,4,opt,name=poc_weight,json=pocWeight,proto3" json:"poc_weight,omitempty"`
	Status           TrainshardNodeStatus `protobuf:"varint,5,opt,name=status,proto3,enum=inference.inference.TrainshardNodeStatus" json:"status,omitempty"`
	ReleasedAtHeight int64                `protobuf:"varint,6,opt,name=released_at_height,json=releasedAtHeight,proto3" json:"released_at_height,omitempty"`
	ReleaseReason    string               `protobuf:"bytes,7,opt,name=release_reason,json=releaseReason,proto3" json:"release_reason,omitempty"`
	// reserved_until_height freezes the release buffer end at release time so
	// epoch-level reads never depend on the current release_buffer_blocks value
	ReservedUntilHeight int64 `protobuf:"varint,8,opt,name=reserved_until_height,json=reservedUntilHeight,proto3" json:"reserved_until_height,omitempty"`
}

func (m *TrainshardReservedNode) Reset()         { *m = TrainshardReservedNode{} }
func (m *TrainshardReservedNode) String() string { return proto.CompactTextString(m) }
func (*TrainshardReservedNode) ProtoMessage()    {}
func (*TrainshardReservedNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_4796ed29b8b523a8, []int{0}
}
func (m *TrainshardReservedNode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrainshardReservedNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrainshardReservedNode.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrainshardReservedNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainshardReservedNode.Merge(m, src)
}
func (m *TrainshardReservedNode) XXX_Size() int {
	return m.Size()
}
func (m *TrainshardReservedNode) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainshardReservedNode.DiscardUnknown(m)
}

var xxx_messageInfo_TrainshardReservedNode proto.InternalMessageInfo

func (m *TrainshardReservedNode) GetParticipant() string {
	if m != nil {
		return m.Participant
	}
	return ""
}

func (m *TrainshardReservedNode) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *TrainshardReservedNode) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *TrainshardReservedNode) GetPocWeight() int64 {
	if m != nil {
		return m.PocWeight
	}
	return 0
}

func (m *TrainshardReservedNode) GetStatus() TrainshardNodeStatus {
	if m != nil {
		return m.Status
	}
	return TrainshardNodeStatus_TRAINSHARD_NODE_STATUS_UNSPECIFIED
}

func (m *TrainshardReservedNode) GetReleasedAtHeight() int64 {
	if m != nil {
		return m.ReleasedAtHeight
	}
	return 0
}

func (m *TrainshardReservedNode) GetReleaseReason() string {
	if m != nil {
		return m.ReleaseReason
	}
	return ""
}

func (m *TrainshardReservedNode) GetReservedUntilHeight() int64 {
	if m != nil {
		return m.ReservedUntilHeight
	}
	return 0
}

type Trainshard struct {
	TrainshardId    uint64                    `protobuf:"varint,1,opt,name=trainshard_id,json=trainshardId,proto3" json:"trainshard_id,omitempty"`
	Creator         string                    `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	GpuProfileId    string                    `protobuf:"bytes,3,opt,name=gpu_profile_id,json=gpuProfileId,proto3" json:"gpu_profile_id,omitempty"`
	Status          TrainshardStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=inference.inference.TrainshardStatus" json:"status,omitempty"`
	CreatedAtHeight int64                     `protobuf:"varint,5,opt,name=created_at_height,json=createdAtHeight,proto3" json:"created_at_height,omitempty"`
	ExpiresAtHeight int64                     `protobuf:"varint,6,opt,name=expires_at_height,json=expiresAtHeight,proto3" json:"expires_at_height,omitempty"`
	ClosedAtHeight  int64                     `protobuf:"varint,7,opt,name=closed_at_height,json=closedAtHeight,proto3" json:"closed_at_height,omitempty"`
	Nodes           []*TrainshardReservedNode `protobuf:"bytes,8,rep,name=nodes,proto3" json:"nodes,omitempty"`
	CloseReason     TrainshardCloseReason     `protobuf:"varint,9,opt,name=close_reason,json=closeReason,proto3,enum=inference.inference.TrainshardCloseReason" json:"close_reason,omitempty"`
	ProposalId      uint64                    `protobuf:"varint,10,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	BaseImage       string                    `protobuf:"bytes,11,opt,name=base_image,json=baseImage,proto3" json:"base_image,omitempty"`
	RunKey          string                    `protobuf:"bytes,12,opt,name=run_key,json=runKey,proto3" json:"run_key,omitempty"`
}

func (m *Trainshard) Reset()         { *m = Trainshard{} }
func (m *Trainshard) String() string { return proto.CompactTextString(m) }
func (*Trainshard) ProtoMessage()    {}
func (*Trainshard) Descriptor() ([]byte, []int) {
	return fileDescriptor_4796ed29b8b523a8, []int{1}
}
func (m *Trainshard) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Trainshard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Trainshard.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Trainshard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trainshard.Merge(m, src)
}
func (m *Trainshard) XXX_Size() int {
	return m.Size()
}
func (m *Trainshard) XXX_DiscardUnknown() {
	xxx_messageInfo_Trainshard.DiscardUnknown(m)
}

var xxx_messageInfo_Trainshard proto.InternalMessageInfo

func (m *Trainshard) GetTrainshardId() uint64 {
	if m != nil {
		return m.TrainshardId
	}
	return 0
}

func (m *Trainshard) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Trainshard) GetGpuProfileId() string {
	if m != nil {
		return m.GpuProfileId
	}
	return ""
}

func (m *Trainshard) GetStatus() TrainshardStatus {
	if m != nil {
		return m.Status
	}
	return TrainshardStatus_TRAINSHARD_STATUS_UNSPECIFIED
}

func (m *Trainshard) GetCreatedAtHeight() int64 {
	if m != nil {
		return m.CreatedAtHeight
	}
	return 0
}

func (m *Trainshard) GetExpiresAtHeight() int64 {
	if m != nil {
		return m.ExpiresAtHeight
	}
	return 0
}

func (m *Trainshard) GetClosedAtHeight() int64 {
	if m != nil {
		return m.ClosedAtHeight
	}
	return 0
}

func (m *Trainshard) GetNodes() []*TrainshardReservedNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Trainshard) GetCloseReason() TrainshardCloseReason {
	if m != nil {
		return m.CloseReason
	}
	return TrainshardCloseReason_TRAINSHARD_CLOSE_REASON_UNSPECIFIED
}

func (m *Trainshard) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *Trainshard) GetBaseImage() string {
	if m != nil {
		return m.BaseImage
	}
	return ""
}

func (m *Trainshard) GetRunKey() string {
	if m != nil {
		return m.RunKey
	}
	return ""
}

type TrainshardProposal struct {
	Creator           string                   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	GpuProfileId      string                   `protobuf:"bytes,2,opt,name=gpu_profile_id,json=gpuProfileId,proto3" json:"gpu_profile_id,omitempty"`
	MaxNodes          uint32                   `protobuf:"varint,3,opt,name=max_nodes,json=maxNodes,proto3" json:"max_nodes,omitempty"`
	MaxDurationBlocks int64                    `protobuf:"varint,4,opt,name=max_duration_blocks,json=maxDurationBlocks,proto3" json:"max_duration_blocks,omitempty"`
	Id                uint64                   `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	Status            TrainshardProposalStatus `protobuf:"varint,6,opt,name=status,proto3,enum=inference.inference.TrainshardProposalStatus" json:"status,omitempty"`
	BaseImage         string                   `protobuf:"bytes,7,opt,name=base_image,json=baseImage,proto3" json:"base_image,omitempty"`
	RunKey            string                   `protobuf:"bytes,8,opt,name=run_key,json=runKey,proto3" json:"run_key,omitempty"`
}

func (m *TrainshardProposal) Reset()         { *m = TrainshardProposal{} }
func (m *TrainshardProposal) String() string { return proto.CompactTextString(m) }
func (*TrainshardProposal) ProtoMessage()    {}
func (*TrainshardProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_4796ed29b8b523a8, []int{2}
}
func (m *TrainshardProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrainshardProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrainshardProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrainshardProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainshardProposal.Merge(m, src)
}
func (m *TrainshardProposal) XXX_Size() int {
	return m.Size()
}
func (m *TrainshardProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainshardProposal.DiscardUnknown(m)
}

var xxx_messageInfo_TrainshardProposal proto.InternalMessageInfo

func (m *TrainshardProposal) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *TrainshardProposal) GetGpuProfileId() string {
	if m != nil {
		return m.GpuProfileId
	}
	return ""
}

func (m *TrainshardProposal) GetMaxNodes() uint32 {
	if m != nil {
		return m.MaxNodes
	}
	return 0
}

func (m *TrainshardProposal) GetMaxDurationBlocks() int64 {
	if m != nil {
		return m.MaxDurationBlocks
	}
	return 0
}

func (m *TrainshardProposal) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TrainshardProposal) GetStatus() TrainshardProposalStatus {
	if m != nil {
		return m.Status
	}
	return TrainshardProposalStatus_TRAINSHARD_PROPOSAL_STATUS_UNSPECIFIED
}

func (m *TrainshardProposal) GetBaseImage() string {
	if m != nil {
		return m.BaseImage
	}
	return ""
}

func (m *TrainshardProposal) GetRunKey() string {
	if m != nil {
		return m.RunKey
	}
	return ""
}

type TrainingParams struct {
	TrainingEnabled               bool     `protobuf:"varint,1,opt,name=training_enabled,json=trainingEnabled,proto3" json:"training_enabled,omitempty"`
	MaxNodesPerShard              uint32   `protobuf:"varint,2,opt,name=max_nodes_per_shard,json=maxNodesPerShard,proto3" json:"max_nodes_per_shard,omitempty"`
	MaxActiveShards               uint32   `protobuf:"varint,3,opt,name=max_active_shards,json=maxActiveShards,proto3" json:"max_active_shards,omitempty"`
	MinDurationBlocks             int64    `protobuf:"varint,4,opt,name=min_duration_blocks,json=minDurationBlocks,proto3" json:"min_duration_blocks,omitempty"`
	MaxDurationBlocks             int64    `protobuf:"varint,5,opt,name=max_duration_blocks,json=maxDurationBlocks,proto3" json:"max_duration_blocks,omitempty"`
	AllowedGpuProfileIds          []string `protobuf:"bytes,6,rep,name=allowed_gpu_profile_ids,json=allowedGpuProfileIds,proto3" json:"allowed_gpu_profile_ids,omitempty"`
	MaxActiveShardsPerCreator     uint32   `protobuf:"varint,7,opt,name=max_active_shards_per_creator,json=maxActiveShardsPerCreator,proto3" json:"max_active_shards_per_creator,omitempty"`
	CreatorCooldownBlocks         int64    `protobuf:"varint,8,opt,name=creator_cooldown_blocks,json=creatorCooldownBlocks,proto3" json:"creator_cooldown_blocks,omitempty"`
	MaxTotalReservedNodes         uint32   `protobuf:"varint,9,opt,name=max_total_reserved_nodes,json=maxTotalReservedNodes,proto3" json:"max_total_reserved_nodes,omitempty"`
	MaxReservedSharePerModelBps   uint32   `protobuf:"varint,10,opt,name=max_reserved_share_per_model_bps,json=maxReservedSharePerModelBps,proto3" json:"max_reserved_share_per_model_bps,omitempty"`
	MaxReservedSharePerProfileBps uint32   `protobuf:"varint,11,opt,name=max_reserved_share_per_profile_bps,json=maxReservedSharePerProfileBps,proto3" json:"max_reserved_share_per_profile_bps,omitempty"`
	MaxExpirationsPerBlock        uint32   `protobuf:"varint,12,opt,name=max_expirations_per_block,json=maxExpirationsPerBlock,proto3" json:"max_expirations_per_block,omitempty"`
	SettledShardRetentionBlocks   int64    `protobuf:"varint,13,opt,name=settled_shard_retention_blocks,json=settledShardRetentionBlocks,proto3" json:"settled_shard_retention_blocks,omitempty"`
	OptInTtlBlocks                int64    `protobuf:"varint,14,opt,name=opt_in_ttl_blocks,json=optInTtlBlocks,proto3" json:"opt_in_ttl_blocks,omitempty"`
	ReleaseBufferBlocks           int64    `protobuf:"varint,15,opt,name=release_buffer_blocks,json=releaseBufferBlocks,proto3" json:"release_buffer_blocks,omitempty"`
}

func (m *TrainingParams) Reset()         { *m = TrainingParams{} }
func (m *TrainingParams) String() string { return proto.CompactTextString(m) }
func (*TrainingParams) ProtoMessage()    {}
func (*TrainingParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_4796ed29b8b523a8, []int{3}
}
func (m *TrainingParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrainingParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrainingParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrainingParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingParams.Merge(m, src)
}
func (m *TrainingParams) XXX_Size() int {
	return m.Size()
}
func (m *TrainingParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingParams.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingParams proto.InternalMessageInfo

func (m *TrainingParams) GetTrainingEnabled() bool {
	if m != nil {
		return m.TrainingEnabled
	}
	return false
}

func (m *TrainingParams) GetMaxNodesPerShard() uint32 {
	if m != nil {
		return m.MaxNodesPerShard
	}
	return 0
}

func (m *TrainingParams) GetMaxActiveShards() uint32 {
	if m != nil {
		return m.MaxActiveShards
	}
	return 0
}

func (m *TrainingParams) GetMinDurationBlocks() int64 {
	if m != nil {
		return m.MinDurationBlocks
	}
	return 0
}

func (m *TrainingParams) GetMaxDurationBlocks() int64 {
	if m != nil {
		return m.MaxDurationBlocks
	}
	return 0
}

func (m *TrainingParams) GetAllowedGpuProfileIds() []string {
	if m != nil {
		return m.AllowedGpuProfileIds
	}
	return nil
}

func (m *TrainingParams) GetMaxActiveShardsPerCreator() uint32 {
	if m != nil {
		return m.MaxActiveShardsPerCreator
	}
	return 0
}

func (m *TrainingParams) GetCreatorCooldownBlocks() int64 {
	if m != nil {
		return m.CreatorCooldownBlocks
	}
	return 0
}

func (m *TrainingParams) GetMaxTotalReservedNodes() uint32 {
	if m != nil {
		return m.MaxTotalReservedNodes
	}
	return 0
}

func (m *TrainingParams) GetMaxReservedSharePerModelBps() uint32 {
	if m != nil {
		return m.MaxReservedSharePerModelBps
	}
	return 0
}

func (m *TrainingParams) GetMaxReservedSharePerProfileBps() uint32 {
	if m != nil {
		return m.MaxReservedSharePerProfileBps
	}
	return 0
}

func (m *TrainingParams) GetMaxExpirationsPerBlock() uint32 {
	if m != nil {
		return m.MaxExpirationsPerBlock
	}
	return 0
}

func (m *TrainingParams) GetSettledShardRetentionBlocks() int64 {
	if m != nil {
		return m.SettledShardRetentionBlocks
	}
	return 0
}

func (m *TrainingParams) GetOptInTtlBlocks() int64 {
	if m != nil {
		return m.OptInTtlBlocks
	}
	return 0
}

func (m *TrainingParams) GetReleaseBufferBlocks() int64 {
	if m != nil {
		return m.ReleaseBufferBlocks
	}
	return 0
}

func init() {
	proto.RegisterEnum("inference.inference.TrainshardStatus", TrainshardStatus_name, TrainshardStatus_value)
	proto.RegisterEnum("inference.inference.TrainshardProposalStatus", TrainshardProposalStatus_name, TrainshardProposalStatus_value)
	proto.RegisterEnum("inference.inference.TrainshardCloseReason", TrainshardCloseReason_name, TrainshardCloseReason_value)
	proto.RegisterEnum("inference.inference.TrainshardNodeStatus", TrainshardNodeStatus_name, TrainshardNodeStatus_value)
	proto.RegisterType((*TrainshardReservedNode)(nil), "inference.inference.TrainshardReservedNode")
	proto.RegisterType((*Trainshard)(nil), "inference.inference.Trainshard")
	proto.RegisterType((*TrainshardProposal)(nil), "inference.inference.TrainshardProposal")
	proto.RegisterType((*TrainingParams)(nil), "inference.inference.TrainingParams")
}

func init() {
	proto.RegisterFile("inference/inference/trainshard.proto", fileDescriptor_4796ed29b8b523a8)
}

var fileDescriptor_4796ed29b8b523a8 = []byte{
	// 1242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0xe5, 0x1f, 0x59, 0x63, 0x4b, 0xa6, 0x37, 0x71, 0xc2, 0x34, 0xb5, 0xe2, 0x38, 0x7f,
	0x8a, 0x92, 0x38, 0x40, 0x8a, 0xb4, 0x68, 0x81, 0x02, 0x95, 0x25, 0xb6, 0x21, 0x62, 0x4b, 0x02,
	0x29, 0xb7, 0x45, 0x2f, 0x0b, 0x8a, 0x5c, 0xcb, 0x44, 0x28, 0x2e, 0xb1, 0x5c, 0x25, 0xca, 0x5b,
	0xb4, 0x40, 0xaf, 0x05, 0xfa, 0x08, 0x3d, 0xb5, 0xaf, 0xd0, 0x63, 0x6e, 0x6d, 0x6f, 0x45, 0x72,
	0xe9, 0x63, 0x14, 0xbb, 0x4b, 0xea, 0xcf, 0x92, 0x7d, 0x23, 0xe7, 0xfb, 0x66, 0x76, 0xe6, 0x9b,
	0xd9, 0x1f, 0xb8, 0x1b, 0x44, 0xa7, 0x84, 0x91, 0xc8, 0x23, 0x4f, 0xc7, 0x5f, 0x9c, 0xb9, 0x41,
	0x94, 0x9c, 0xb9, 0xcc, 0x3f, 0x88, 0x19, 0xe5, 0x14, 0x5d, 0x19, 0x61, 0x07, 0xa3, 0xaf, 0x8f,
	0xae, 0xf6, 0x68, 0x8f, 0x4a, 0xfc, 0xa9, 0xf8, 0x52, 0xd4, 0xfd, 0x7f, 0x72, 0x70, 0xad, 0x33,
	0xf2, 0xb7, 0x49, 0x42, 0xd8, 0x6b, 0xe2, 0x37, 0xa9, 0x4f, 0xd0, 0x1e, 0x6c, 0xc4, 0x2e, 0xe3,
	0x81, 0x17, 0xc4, 0x6e, 0xc4, 0x0d, 0x6d, 0x4f, 0xab, 0x14, 0xec, 0x49, 0x13, 0xba, 0x0e, 0xf9,
	0x88, 0xfa, 0x04, 0x07, 0xbe, 0x91, 0x93, 0xe8, 0x9a, 0xf8, 0xb5, 0x7c, 0x74, 0x03, 0xd6, 0xfb,
	0xd4, 0x27, 0xa1, 0x40, 0x96, 0x25, 0x92, 0x97, 0xff, 0x96, 0x8f, 0x76, 0x01, 0x62, 0xea, 0xe1,
	0x37, 0x24, 0xe8, 0x9d, 0x71, 0x63, 0x65, 0x4f, 0xab, 0x2c, 0xdb, 0x85, 0x98, 0x7a, 0xdf, 0x49,
	0x03, 0xaa, 0xc1, 0x5a, 0xc2, 0x5d, 0x3e, 0x48, 0x8c, 0xd5, 0x3d, 0xad, 0x52, 0x7a, 0xf6, 0xf0,
	0x60, 0x4e, 0x2d, 0x07, 0xe3, 0x8c, 0x45, 0xa6, 0x8e, 0x74, 0xb0, 0x53, 0x47, 0xf4, 0x18, 0x10,
	0x23, 0x21, 0x71, 0x13, 0xe2, 0x63, 0x97, 0xe3, 0x33, 0xb5, 0xd2, 0x9a, 0x5c, 0x49, 0xcf, 0x90,
	0x1a, 0x7f, 0xa1, 0x16, 0xbc, 0x07, 0xa5, 0xd4, 0x86, 0x19, 0x71, 0x13, 0x1a, 0x19, 0x79, 0x99,
	0x70, 0x31, 0xb5, 0xda, 0xd2, 0x88, 0x9e, 0xc1, 0x0e, 0x4b, 0xc5, 0xc1, 0x83, 0x88, 0x07, 0x61,
	0x16, 0x77, 0x5d, 0xc6, 0xbd, 0x92, 0x81, 0x27, 0x02, 0x53, 0xa1, 0xf7, 0x7f, 0x59, 0x01, 0x18,
	0x67, 0x8a, 0xee, 0x40, 0x71, 0xdc, 0x29, 0xa1, 0x8c, 0x50, 0x74, 0xc5, 0xde, 0x1c, 0x1b, 0x2d,
	0x1f, 0x19, 0x90, 0xf7, 0x18, 0x71, 0x39, 0x65, 0xa9, 0xa4, 0xd9, 0x2f, 0xba, 0x0b, 0xa5, 0x5e,
	0x3c, 0xc0, 0x31, 0xa3, 0xa7, 0x41, 0x48, 0xc6, 0xca, 0x6e, 0xf6, 0xe2, 0x41, 0x5b, 0x19, 0x2d,
	0x1f, 0x7d, 0x39, 0xd2, 0x6f, 0x45, 0xea, 0x77, 0xef, 0x12, 0xfd, 0x66, 0xb4, 0xab, 0xc2, 0xb6,
	0x5c, 0x6f, 0x4a, 0xba, 0x55, 0x59, 0xe2, 0x56, 0x0a, 0x8c, 0x94, 0xab, 0xc2, 0x36, 0x19, 0xc6,
	0x01, 0x23, 0xc9, 0x39, 0x99, 0xb7, 0x52, 0x60, 0xc4, 0xad, 0x80, 0xee, 0x85, 0x74, 0xba, 0x23,
	0x79, 0x49, 0x2d, 0x29, 0xfb, 0x88, 0x59, 0x83, 0x55, 0x31, 0x44, 0x89, 0xb1, 0xbe, 0xb7, 0x5c,
	0xd9, 0x78, 0xf6, 0xe8, 0x92, 0xfc, 0x27, 0x27, 0xd6, 0x56, 0x9e, 0xe8, 0x18, 0x36, 0x65, 0xd0,
	0xac, 0xa1, 0x05, 0xa9, 0x44, 0xf5, 0x92, 0x48, 0x75, 0xe1, 0xa2, 0xba, 0x6d, 0x6f, 0x78, 0xe3,
	0x1f, 0x74, 0x0b, 0x36, 0x62, 0x46, 0x63, 0x9a, 0xb8, 0x72, 0x9e, 0x41, 0x76, 0x0d, 0x32, 0x93,
	0x1a, 0xe9, 0xae, 0x98, 0x9f, 0xa0, 0xef, 0xf6, 0x88, 0xb1, 0x21, 0xbb, 0x52, 0x10, 0x16, 0x4b,
	0x18, 0xc4, 0x2e, 0x61, 0x83, 0x08, 0xbf, 0x22, 0x6f, 0x8d, 0x4d, 0xb5, 0x4b, 0xd8, 0x20, 0x7a,
	0x49, 0xde, 0xee, 0xff, 0x96, 0x03, 0x34, 0x5e, 0xbf, 0x9d, 0x06, 0x9c, 0x1c, 0x01, 0xed, 0xb2,
	0x11, 0xc8, 0xcd, 0x19, 0x81, 0x9b, 0x50, 0xe8, 0xbb, 0x43, 0xac, 0x54, 0x14, 0x33, 0x52, 0xb4,
	0xd7, 0xfb, 0xee, 0xb0, 0x29, 0xb5, 0x39, 0x80, 0x2b, 0x02, 0xf4, 0x07, 0xcc, 0xe5, 0x01, 0x8d,
	0x70, 0x37, 0xa4, 0xde, 0xab, 0x24, 0xdd, 0x87, 0xdb, 0x7d, 0x77, 0xd8, 0x48, 0x91, 0x43, 0x09,
	0xa0, 0x12, 0xe4, 0x02, 0x5f, 0x4e, 0xc0, 0x8a, 0x9d, 0x0b, 0x7c, 0x64, 0x8e, 0xe6, 0x6b, 0x4d,
	0xaa, 0xfa, 0xe4, 0x12, 0x55, 0xb3, 0xaa, 0x66, 0xe6, 0x6c, 0x5a, 0xb2, 0xfc, 0x05, 0x92, 0xad,
	0x4f, 0x49, 0xf6, 0xd7, 0x1a, 0x94, 0x64, 0xf0, 0x20, 0xea, 0xb5, 0x5d, 0xe6, 0xf6, 0x13, 0xf4,
	0x10, 0x74, 0x9e, 0x5a, 0x30, 0x89, 0xdc, 0x6e, 0x48, 0xd4, 0xce, 0x5a, 0xb7, 0xb7, 0x32, 0xbb,
	0xa9, 0xcc, 0xe8, 0x89, 0x2a, 0x5e, 0x2a, 0x83, 0x63, 0xc2, 0xb0, 0x4c, 0x51, 0x8a, 0x58, 0xb4,
	0xf5, 0x4c, 0xa3, 0x36, 0x61, 0x8e, 0xdc, 0xb0, 0x55, 0x10, 0x82, 0x60, 0xd7, 0xe3, 0xc1, 0x6b,
	0xa2, 0xb8, 0x99, 0xa0, 0x5b, 0x7d, 0x77, 0x58, 0x93, 0x76, 0x49, 0x55, 0xba, 0x06, 0xd1, 0x42,
	0x5d, 0x83, 0x68, 0x46, 0xd7, 0x05, 0x7d, 0x58, 0x5d, 0xd4, 0x87, 0xe7, 0x70, 0xdd, 0x0d, 0x43,
	0xfa, 0x86, 0xf8, 0x78, 0x7a, 0x04, 0x44, 0x23, 0x96, 0x2b, 0x05, 0xfb, 0x6a, 0x0a, 0x7f, 0x33,
	0x31, 0x0a, 0x09, 0xfa, 0x0a, 0x76, 0xcf, 0x95, 0x20, 0x2b, 0xcf, 0x26, 0x2c, 0x2f, 0xcb, 0xb9,
	0x31, 0x53, 0x4e, 0x9b, 0xb0, 0x7a, 0x3a, 0x73, 0x9f, 0xc2, 0xf5, 0x94, 0x8b, 0x3d, 0x4a, 0x43,
	0x9f, 0xbe, 0x19, 0x25, 0xab, 0x8e, 0xbe, 0x9d, 0x14, 0xae, 0xa7, 0x68, 0x9a, 0xf0, 0x67, 0x60,
	0x88, 0x95, 0x39, 0xe5, 0x6e, 0x88, 0x47, 0x47, 0xa7, 0x1a, 0xca, 0x82, 0x5c, 0x74, 0xa7, 0xef,
	0x0e, 0x3b, 0x02, 0x9e, 0xdc, 0xc3, 0x09, 0x32, 0x61, 0x4f, 0x38, 0x8e, 0x5c, 0x44, 0xd2, 0x44,
	0xe6, 0xac, 0xae, 0x94, 0x6e, 0x9c, 0xc8, 0x3d, 0x58, 0xb4, 0x6f, 0xf6, 0xdd, 0x61, 0xe6, 0x2b,
	0xf2, 0x26, 0x6d, 0xc2, 0x8e, 0x05, 0xe7, 0x30, 0x4e, 0x90, 0x05, 0xfb, 0x0b, 0xc2, 0x64, 0xda,
	0x89, 0x40, 0x1b, 0x32, 0xd0, 0xee, 0x9c, 0x40, 0xa9, 0x88, 0x22, 0xd4, 0xe7, 0x20, 0xf4, 0xc1,
	0xf2, 0x4c, 0x93, 0x3d, 0x51, 0x12, 0x4a, 0x15, 0xe4, 0x96, 0x2e, 0xda, 0xd7, 0xfa, 0xee, 0xd0,
	0x1c, 0xe3, 0x6d, 0xc2, 0xa4, 0x0c, 0xa8, 0x0e, 0xe5, 0x84, 0x70, 0x1e, 0xa6, 0x09, 0xf8, 0x98,
	0x11, 0x4e, 0xa2, 0xc9, 0x8e, 0x17, 0xa5, 0x88, 0x37, 0x53, 0x96, 0xa3, 0xce, 0xb4, 0x94, 0x93,
	0x4a, 0xf9, 0x10, 0xb6, 0x69, 0xcc, 0x71, 0x10, 0x61, 0xce, 0xc3, 0xcc, 0xaf, 0xa4, 0x4e, 0x4f,
	0x1a, 0x73, 0x2b, 0xea, 0xf0, 0x30, 0xa5, 0xca, 0x6b, 0x4a, 0xdd, 0x66, 0xdd, 0xc1, 0xe9, 0x69,
	0x96, 0x65, 0x62, 0x6c, 0x65, 0xd7, 0x94, 0x04, 0x0f, 0x25, 0xa6, 0x7c, 0xbe, 0x58, 0xf9, 0xef,
	0xd7, 0x5b, 0x5a, 0xf5, 0x27, 0x0d, 0xf4, 0xd9, 0x6b, 0x01, 0xdd, 0x86, 0xdd, 0x8e, 0x5d, 0xb3,
	0x9a, 0xce, 0x8b, 0x9a, 0xdd, 0xc0, 0x4e, 0xa7, 0xd6, 0x39, 0x71, 0xf0, 0x49, 0xd3, 0x69, 0x9b,
	0x75, 0xeb, 0x6b, 0xcb, 0x6c, 0xe8, 0x4b, 0xe8, 0x63, 0x30, 0xce, 0x53, 0x6a, 0xf5, 0x8e, 0xf5,
	0xad, 0xa9, 0x6b, 0x68, 0x17, 0x6e, 0x9c, 0x47, 0x1d, 0xb3, 0xd3, 0x39, 0x32, 0x1b, 0x7a, 0x6e,
	0x3e, 0x6c, 0x7e, 0xdf, 0xb6, 0x6c, 0xb3, 0xa1, 0x2f, 0x57, 0x7f, 0xd6, 0xc0, 0x58, 0x74, 0x94,
	0xa0, 0x2a, 0xdc, 0x9f, 0xf0, 0x6d, 0xdb, 0xad, 0x76, 0xcb, 0xa9, 0x1d, 0xcd, 0x4f, 0xf2, 0x0e,
	0xdc, 0xba, 0x80, 0xdb, 0x6a, 0x9b, 0x4d, 0x5d, 0x43, 0x0f, 0xe0, 0xce, 0x05, 0xa4, 0x7a, 0xab,
	0xe9, 0x9c, 0x1c, 0x8b, 0xac, 0xab, 0x7f, 0x68, 0xb0, 0x33, 0xf7, 0xde, 0x98, 0x09, 0x51, 0x3f,
	0x6a, 0x39, 0x26, 0xb6, 0xcd, 0x9a, 0xd3, 0x6a, 0x5e, 0x98, 0xd0, 0x14, 0x31, 0x53, 0x47, 0xbb,
	0x88, 0xd4, 0xb1, 0x8e, 0xcd, 0xd6, 0x49, 0x47, 0xcf, 0xa1, 0x47, 0xf0, 0x60, 0x11, 0xa9, 0xd9,
	0x4a, 0x1b, 0x81, 0x9b, 0xad, 0x86, 0xe9, 0xe8, 0xcb, 0xd5, 0xdf, 0x35, 0xb8, 0x3a, 0xef, 0xed,
	0x84, 0xee, 0xc3, 0xfe, 0x44, 0x14, 0x41, 0x9f, 0x2f, 0xe4, 0xf4, 0x40, 0x4c, 0xf2, 0x46, 0x2d,
	0xbf, 0x07, 0xb7, 0x17, 0x51, 0x4e, 0x3a, 0xad, 0x97, 0x56, 0xfd, 0xa5, 0x6c, 0xfd, 0x63, 0xa8,
	0x2c, 0xa0, 0xd9, 0xe6, 0x91, 0x59, 0x73, 0xcc, 0x06, 0x6e, 0x35, 0x55, 0x3d, 0xfa, 0xf2, 0x61,
	0xeb, 0xcf, 0xf7, 0x65, 0xed, 0xdd, 0xfb, 0xb2, 0xf6, 0xef, 0xfb, 0xb2, 0xf6, 0xe3, 0x87, 0xf2,
	0xd2, 0xbb, 0x0f, 0xe5, 0xa5, 0xbf, 0x3f, 0x94, 0x97, 0x7e, 0x78, 0xde, 0x0b, 0xf8, 0xd9, 0xa0,
	0x7b, 0xe0, 0xd1, 0xfe, 0xd3, 0x98, 0x51, 0x7f, 0xe0, 0xf1, 0xc4, 0x0b, 0x66, 0x5e, 0xc8, 0xc3,
	0xc9, 0xd7, 0xf2, 0xdb, 0x98, 0x24, 0xdd, 0x35, 0xf9, 0xfc, 0xfd, 0xe4, 0xff, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x52, 0xa7, 0xd9, 0x59, 0x51, 0x0b, 0x00, 0x00,
}

func (this *TrainingParams) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TrainingParams)
	if !ok {
		that2, ok := that.(TrainingParams)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TrainingEnabled != that1.TrainingEnabled {
		return false
	}
	if this.MaxNodesPerShard != that1.MaxNodesPerShard {
		return false
	}
	if this.MaxActiveShards != that1.MaxActiveShards {
		return false
	}
	if this.MinDurationBlocks != that1.MinDurationBlocks {
		return false
	}
	if this.MaxDurationBlocks != that1.MaxDurationBlocks {
		return false
	}
	if len(this.AllowedGpuProfileIds) != len(that1.AllowedGpuProfileIds) {
		return false
	}
	for i := range this.AllowedGpuProfileIds {
		if this.AllowedGpuProfileIds[i] != that1.AllowedGpuProfileIds[i] {
			return false
		}
	}
	if this.MaxActiveShardsPerCreator != that1.MaxActiveShardsPerCreator {
		return false
	}
	if this.CreatorCooldownBlocks != that1.CreatorCooldownBlocks {
		return false
	}
	if this.MaxTotalReservedNodes != that1.MaxTotalReservedNodes {
		return false
	}
	if this.MaxReservedSharePerModelBps != that1.MaxReservedSharePerModelBps {
		return false
	}
	if this.MaxReservedSharePerProfileBps != that1.MaxReservedSharePerProfileBps {
		return false
	}
	if this.MaxExpirationsPerBlock != that1.MaxExpirationsPerBlock {
		return false
	}
	if this.SettledShardRetentionBlocks != that1.SettledShardRetentionBlocks {
		return false
	}
	if this.OptInTtlBlocks != that1.OptInTtlBlocks {
		return false
	}
	if this.ReleaseBufferBlocks != that1.ReleaseBufferBlocks {
		return false
	}
	return true
}
func (m *TrainshardReservedNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrainshardReservedNode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrainshardReservedNode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReservedUntilHeight != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.ReservedUntilHeight))
		i--
		dAtA[i] = 0x40
	}
	if len(m.ReleaseReason) > 0 {
		i -= len(m.ReleaseReason)
		copy(dAtA[i:], m.ReleaseReason)
		i = encodeVarintTrainshard(dAtA, i, uint64(len(m.ReleaseReason)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ReleasedAtHeight != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.ReleasedAtHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.Status != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if m.PocWeight != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.PocWeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintTrainshard(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintTrainshard(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Participant) > 0 {
		i -= len(m.Participant)
		copy(dAtA[i:], m.Participant)
		i = encodeVarintTrainshard(dAtA, i, uint64(len(m.Participant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Trainshard) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Trainshard) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Trainshard) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RunKey) > 0 {
		i -= len(m.RunKey)
		copy(dAtA[i:], m.RunKey)
		i = encodeVarintTrainshard(dAtA, i, uint64(len(m.RunKey)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.BaseImage) > 0 {
		i -= len(m.BaseImage)
		copy(dAtA[i:], m.BaseImage)
		i = encodeVarintTrainshard(dAtA, i, uint64(len(m.BaseImage)))
		i--
		dAtA[i] = 0x5a
	}
	if m.ProposalId != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x50
	}
	if m.CloseReason != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.CloseReason))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Nodes) > 0 {
		for iNdEx := len(m.Nodes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Nodes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTrainshard(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.ClosedAtHeight != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.ClosedAtHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.ExpiresAtHeight != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.ExpiresAtHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.CreatedAtHeight != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.CreatedAtHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.Status != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if len(m.GpuProfileId) > 0 {
		i -= len(m.GpuProfileId)
		copy(dAtA[i:], m.GpuProfileId)
		i = encodeVarintTrainshard(dAtA, i, uint64(len(m.GpuProfileId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTrainshard(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.TrainshardId != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.TrainshardId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TrainshardProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrainshardProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrainshardProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RunKey) > 0 {
		i -= len(m.RunKey)
		copy(dAtA[i:], m.RunKey)
		i = encodeVarintTrainshard(dAtA, i, uint64(len(m.RunKey)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.BaseImage) > 0 {
		i -= len(m.BaseImage)
		copy(dAtA[i:], m.BaseImage)
		i = encodeVarintTrainshard(dAtA, i, uint64(len(m.BaseImage)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Status != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if m.Id != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxDurationBlocks != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.MaxDurationBlocks))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxNodes != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.MaxNodes))
		i--
		dAtA[i] = 0x18
	}
	if len(m.GpuProfileId) > 0 {
		i -= len(m.GpuProfileId)
		copy(dAtA[i:], m.GpuProfileId)
		i = encodeVarintTrainshard(dAtA, i, uint64(len(m.GpuProfileId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTrainshard(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TrainingParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrainingParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrainingParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReleaseBufferBlocks != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.ReleaseBufferBlocks))
		i--
		dAtA[i] = 0x78
	}
	if m.OptInTtlBlocks != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.OptInTtlBlocks))
		i--
		dAtA[i] = 0x70
	}
	if m.SettledShardRetentionBlocks != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.SettledShardRetentionBlocks))
		i--
		dAtA[i] = 0x68
	}
	if m.MaxExpirationsPerBlock != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.MaxExpirationsPerBlock))
		i--
		dAtA[i] = 0x60
	}
	if m.MaxReservedSharePerProfileBps != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.MaxReservedSharePerProfileBps))
		i--
		dAtA[i] = 0x58
	}
	if m.MaxReservedSharePerModelBps != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.MaxReservedSharePerModelBps))
		i--
		dAtA[i] = 0x50
	}
	if m.MaxTotalReservedNodes != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.MaxTotalReservedNodes))
		i--
		dAtA[i] = 0x48
	}
	if m.CreatorCooldownBlocks != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.CreatorCooldownBlocks))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxActiveShardsPerCreator != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.MaxActiveShardsPerCreator))
		i--
		dAtA[i] = 0x38
	}
	if len(m.AllowedGpuProfileIds) > 0 {
		for iNdEx := len(m.AllowedGpuProfileIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedGpuProfileIds[iNdEx])
			copy(dAtA[i:], m.AllowedGpuProfileIds[iNdEx])
			i = encodeVarintTrainshard(dAtA, i, uint64(len(m.AllowedGpuProfileIds[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.MaxDurationBlocks != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.MaxDurationBlocks))
		i--
		dAtA[i] = 0x28
	}
	if m.MinDurationBlocks != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.MinDurationBlocks))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxActiveShards != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.MaxActiveShards))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxNodesPerShard != 0 {
		i = encodeVarintTrainshard(dAtA, i, uint64(m.MaxNodesPerShard))
		i--
		dAtA[i] = 0x10
	}
	if m.TrainingEnabled {
		i--
		if m.TrainingEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTrainshard(dAtA []byte, offset int, v uint64) int {
	offset -= sovTrainshard(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TrainshardReservedNode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Participant)
	if l > 0 {
		n += 1 + l + sovTrainshard(uint64(l))
	}
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovTrainshard(uint64(l))
	}
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovTrainshard(uint64(l))
	}
	if m.PocWeight != 0 {
		n += 1 + sovTrainshard(uint64(m.PocWeight))
	}
	if m.Status != 0 {
		n += 1 + sovTrainshard(uint64(m.Status))
	}
	if m.ReleasedAtHeight != 0 {
		n += 1 + sovTrainshard(uint64(m.ReleasedAtHeight))
	}
	l = len(m.ReleaseReason)
	if l > 0 {
		n += 1 + l + sovTrainshard(uint64(l))
	}
	if m.ReservedUntilHeight != 0 {
		n += 1 + sovTrainshard(uint64(m.ReservedUntilHeight))
	}
	return n
}

func (m *Trainshard) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrainshardId != 0 {
		n += 1 + sovTrainshard(uint64(m.TrainshardId))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTrainshard(uint64(l))
	}
	l = len(m.GpuProfileId)
	if l > 0 {
		n += 1 + l + sovTrainshard(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTrainshard(uint64(m.Status))
	}
	if m.CreatedAtHeight != 0 {
		n += 1 + sovTrainshard(uint64(m.CreatedAtHeight))
	}
	if m.ExpiresAtHeight != 0 {
		n += 1 + sovTrainshard(uint64(m.ExpiresAtHeight))
	}
	if m.ClosedAtHeight != 0 {
		n += 1 + sovTrainshard(uint64(m.ClosedAtHeight))
	}
	if len(m.Nodes) > 0 {
		for _, e := range m.Nodes {
			l = e.Size()
			n += 1 + l + sovTrainshard(uint64(l))
		}
	}
	if m.CloseReason != 0 {
		n += 1 + sovTrainshard(uint64(m.CloseReason))
	}
	if m.ProposalId != 0 {
		n += 1 + sovTrainshard(uint64(m.ProposalId))
	}
	l = len(m.BaseImage)
	if l > 0 {
		n += 1 + l + sovTrainshard(uint64(l))
	}
	l = len(m.RunKey)
	if l > 0 {
		n += 1 + l + sovTrainshard(uint64(l))
	}
	return n
}

func (m *TrainshardProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTrainshard(uint64(l))
	}
	l = len(m.GpuProfileId)
	if l > 0 {
		n += 1 + l + sovTrainshard(uint64(l))
	}
	if m.MaxNodes != 0 {
		n += 1 + sovTrainshard(uint64(m.MaxNodes))
	}
	if m.MaxDurationBlocks != 0 {
		n += 1 + sovTrainshard(uint64(m.MaxDurationBlocks))
	}
	if m.Id != 0 {
		n += 1 + sovTrainshard(uint64(m.Id))
	}
	if m.Status != 0 {
		n += 1 + sovTrainshard(uint64(m.Status))
	}
	l = len(m.BaseImage)
	if l > 0 {
		n += 1 + l + sovTrainshard(uint64(l))
	}
	l = len(m.RunKey)
	if l > 0 {
		n += 1 + l + sovTrainshard(uint64(l))
	}
	return n
}

func (m *TrainingParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrainingEnabled {
		n += 2
	}
	if m.MaxNodesPerShard != 0 {
		n += 1 + sovTrainshard(uint64(m.MaxNodesPerShard))
	}
	if m.MaxActiveShards != 0 {
		n += 1 + sovTrainshard(uint64(m.MaxActiveShards))
	}
	if m.MinDurationBlocks != 0 {
		n += 1 + sovTrainshard(uint64(m.MinDurationBlocks))
	}
	if m.MaxDurationBlocks != 0 {
		n += 1 + sovTrainshard(uint64(m.MaxDurationBlocks))
	}
	if len(m.AllowedGpuProfileIds) > 0 {
		for _, s := range m.AllowedGpuProfileIds {
			l = len(s)
			n += 1 + l + sovTrainshard(uint64(l))
		}
	}
	if m.MaxActiveShardsPerCreator != 0 {
		n += 1 + sovTrainshard(uint64(m.MaxActiveShardsPerCreator))
	}
	if m.CreatorCooldownBlocks != 0 {
		n += 1 + sovTrainshard(uint64(m.CreatorCooldownBlocks))
	}
	if m.MaxTotalReservedNodes != 0 {
		n += 1 + sovTrainshard(uint64(m.MaxTotalReservedNodes))
	}
	if m.MaxReservedSharePerModelBps != 0 {
		n += 1 + sovTrainshard(uint64(m.MaxReservedSharePerModelBps))
	}
	if m.MaxReservedSharePerProfileBps != 0 {
		n += 1 + sovTrainshard(uint64(m.MaxReservedSharePerProfileBps))
	}
	if m.MaxExpirationsPerBlock != 0 {
		n += 1 + sovTrainshard(uint64(m.MaxExpirationsPerBlock))
	}
	if m.SettledShardRetentionBlocks != 0 {
		n += 1 + sovTrainshard(uint64(m.SettledShardRetentionBlocks))
	}
	if m.OptInTtlBlocks != 0 {
		n += 1 + sovTrainshard(uint64(m.OptInTtlBlocks))
	}
	if m.ReleaseBufferBlocks != 0 {
		n += 1 + sovTrainshard(uint64(m.ReleaseBufferBlocks))
	}
	return n
}

func sovTrainshard(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTrainshard(x uint64) (n int) {
	return sovTrainshard(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TrainshardReservedNode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrainshard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrainshardReservedNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrainshardReservedNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocWeight", wireType)
			}
			m.PocWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocWeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= TrainshardNodeStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleasedAtHeight", wireType)
			}
			m.ReleasedAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReleasedAtHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleaseReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReleaseReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservedUntilHeight", wireType)
			}
			m.ReservedUntilHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReservedUntilHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTrainshard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrainshard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Trainshard) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrainshard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Trainshard: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Trainshard: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrainshardId", wireType)
			}
			m.TrainshardId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrainshardId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GpuProfileId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GpuProfileId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= TrainshardStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtHeight", wireType)
			}
			m.CreatedAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAtHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAtHeight", wireType)
			}
			m.ExpiresAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAtHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClosedAtHeight", wireType)
			}
			m.ClosedAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClosedAtHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nodes = append(m.Nodes, &TrainshardReservedNode{})
			if err := m.Nodes[len(m.Nodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CloseReason", wireType)
			}
			m.CloseReason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CloseReason |= TrainshardCloseReason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseImage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseImage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RunKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RunKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrainshard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrainshard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TrainshardProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrainshard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrainshardProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrainshardProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GpuProfileId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GpuProfileId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNodes", wireType)
			}
			m.MaxNodes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxNodes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDurationBlocks", wireType)
			}
			m.MaxDurationBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDurationBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= TrainshardProposalStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseImage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseImage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RunKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RunKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrainshard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrainshard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TrainingParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrainshard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrainingParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrainingParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrainingEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TrainingEnabled = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNodesPerShard", wireType)
			}
			m.MaxNodesPerShard = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxNodesPerShard |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxActiveShards", wireType)
			}
			m.MaxActiveShards = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxActiveShards |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDurationBlocks", wireType)
			}
			m.MinDurationBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDurationBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDurationBlocks", wireType)
			}
			m.MaxDurationBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDurationBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedGpuProfileIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainshard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainshard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedGpuProfileIds = append(m.AllowedGpuProfileIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxActiveShardsPerCreator", wireType)
			}
			m.MaxActiveShardsPerCreator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxActiveShardsPerCreator |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorCooldownBlocks", wireType)
			}
			m.CreatorCooldownBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatorCooldownBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTotalReservedNodes", wireType)
			}
			m.MaxTotalReservedNodes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTotalReservedNodes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReservedSharePerModelBps", wireType)
			}
			m.MaxReservedSharePerModelBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxReservedSharePerModelBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReservedSharePerProfileBps", wireType)
			}
			m.MaxReservedSharePerProfileBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxReservedSharePerProfileBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxExpirationsPerBlock", wireType)
			}
			m.MaxExpirationsPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxExpirationsPerBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettledShardRetentionBlocks", wireType)
			}
			m.SettledShardRetentionBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SettledShardRetentionBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OptInTtlBlocks", wireType)
			}
			m.OptInTtlBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OptInTtlBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleaseBufferBlocks", wireType)
			}
			m.ReleaseBufferBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReleaseBufferBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTrainshard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrainshard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTrainshard(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTrainshard
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrainshard
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTrainshard
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTrainshard
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTrainshard
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTrainshard        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTrainshard          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTrainshard = fmt.Errorf("proto: unexpected end of group")
)
